# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f400294a48a4912b56a7c2a1940e19e77a45b215819cbdeb8db4f5d4dd63cd948f140aad5c8eff818b1051fc9ab62abfb4548f251b378d53a352579ddbc911f

test:
  secret_key_base: 4703978f6a599f69b69e300baa3bf0e747609209d46b8c2177a9e450d805d30c860aa9bb5b63ef51aabad61799b0a3bf8f4bc333b66bf9bf761c4b707e372506

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
